import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Start',
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules',
        },
      ],
    },
    {
      type: 'category',
      label: 'Especificações',
      items: [
        {
          type: 'autogenerated',
          dirName: 'specifications',
        },
      ],
    },
  ],
  communitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'community',
    },
  ],
  tutorialsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],
};

export default sidebars;

