import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Início',
    },
    {
      type: 'category',
      label: 'Módulos',
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules',
        },
      ],
    },
  ],
  communitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'community',
    },
  ],
};

export default sidebars;

